# Generated by Django 5.1.6 on 2025-02-16 15:08

import apps.customers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[apps.customers.validators.validate_cnpj], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(max_length=11, validators=[apps.customers.validators.validate_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=11, validators=[apps.customers.validators.validate_phone], verbose_name='Telefone'),
        ),
    ]
