# Generated by Django 6.0.3 on 2026-06-01 20:00

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('users', '0002_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_borrowed', models.DecimalField(decimal_places=2, help_text='Valor inicial emprestado', max_digits=10)),
                ('loan_date', models.DateField(default=django.utils.timezone.now, help_text='Data do empréstimo')),
                ('due_date', models.DateField(help_text='Data combinada para pagamento')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Taxa de juros em percentual (ex: 5.00 para 5%)', max_digits=5)),
                ('num_installments', models.IntegerField(default=1, help_text='Número de parcelas')),
                ('first_payment_date', models.DateField(help_text='Data do primeiro pagamento')),
                ('final_amount', models.DecimalField(decimal_places=2, editable=False, help_text='Valor final com juros', max_digits=10)),
                ('installment_amount', models.DecimalField(decimal_places=2, editable=False, help_text='Valor de cada parcela', max_digits=10)),
                ('total_interest', models.DecimalField(decimal_places=2, editable=False, help_text='Total de juros a pagar', max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('paid', 'Pago'), ('overdue', 'Atrasado'), ('cancelled', 'Cancelado')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionais sobre o empréstimo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='users.company')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='customers.debtor')),
            ],
            options={
                'verbose_name_plural': 'Loans',
                'ordering': ['-loan_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(help_text='Número da parcela (1, 2, 3...)')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor da parcela', max_digits=10)),
                ('due_date', models.DateField(help_text='Data prevista para pagamento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('overdue', 'Atrasado')], default='pending', max_length=20)),
                ('paid_date', models.DateField(blank=True, help_text='Data em que foi realmente pago', null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Valor que foi efetivamente pago (em caso de variação)', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas sobre o pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan')),
            ],
            options={
                'verbose_name_plural': 'Loan Payments',
                'ordering': ['loan', 'installment_number'],
                'unique_together': {('loan', 'installment_number')},
            },
        ),
    ]
